### ISSUE TITLE
Automatically resolve float type in RNG.

### ISSUE THREAD

**Issue by anadodik** [mitsuba-renderer/enoki#102]
Currently, the following breaks:
```
enoki::PCG32<enoki::DynamicArray<enoki::Packet<double, PacketSize>>> rng;
rng.next_float32();
```

It would be nice if there was a function which would automatically pick the correct overload between next_float32 and next_float64() depending on the size of the template parameter.

Willing to make a pull request if there is interest. 😊

**Comment by wjakob** [comment]
I think @Speierers is about to do the same.

**Comment by Speierers** [comment]
Hi @anadodik,

This should be what you are looking for: cd3a312
