### ISSUE TITLE
Force enoki::Array<float, 3> to be 12 bytes

### ISSUE THREAD

**Issue by rohan-sawhney** [mitsuba-renderer/enoki#105]
Hi, enoki seems to pad arrays of size 3 with an extra zero for improved vectorization. Is there a way to disable this feature?

**Comment by wjakob** [comment]
Yes: -DENOKI_DISABLE_VECTORIZATION

**Comment by rohan-sawhney** [comment]
Thanks! Is this specifically for arrays of size 3, or does it impact vectorization elsewhere as well? I'd specifically like to turn off vectorization for arrays of size 3.

**Comment by wjakob** [comment]
That will turn of vectorization everywhere. We don't currently expose a way to do that just for size 3, but it could be an interesting addition. A lot of work is currently going into a major redesign of the Enoki internals, and we can look into that once that's done (but probably not for a few months)

**Comment by rohan-sawhney** [comment]
Sounds good, thanks.
