### ISSUE TITLE
sign documentation is wrong

### ISSUE THREAD

**Issue by tomasiser** [mitsuba-renderer/enoki#109]
Hello, in the [reference documentation](https://enoki.readthedocs.io/en/master/reference.html), there is a very weird definition of the signum function for `sign` that does not return -1:

![image](https://user-images.githubusercontent.com/10374559/95851073-08242d00-0d52-11eb-9778-6e16d089088a.png)

However, when you actually use the function, it returns -1 just fine, as per the definition of [`std::copysign`](https://en.cppreference.com/w/cpp/numeric/math/copysign).

Can also be reproduced in Python:
![image](https://user-images.githubusercontent.com/10374559/95851558-ad3f0580-0d52-11eb-86ce-22a33ba6fbed.png)

**Comment by wjakob** [comment]
fixed via #110
