### ISSUE TITLE
Difference between this enoki and wjakob/enoki

### ISSUE THREAD

**Issue by gergol** [mitsuba-renderer/enoki#112]
I'm using enoki in one of my projects and while skimming through the issues I stumbled across `wjakob/enoki` which seems to be more active recently but looks quite a bit different from this one here. I was wondering why there are two "versions" of enoki and what's the difference between them? Will they be merged at some point, or will this one here eventually be replaced by the other one?

**Comment by wjakob** [comment]
This one here will be replaced by `wjakob/enoki`.

**Comment by gergol** [comment]
Thanks, good to know. Will `wjakob/enoki` eventually come with a NEON backend?
