### ISSUE TITLE
The behavior of enoki::hsum does not correspond to the documentation

### ISSUE THREAD

**Issue by RiverIntheSky** [mitsuba-renderer/enoki#113]
[The documentation](https://enoki.readthedocs.io/en/master/reference.html?highlight=hsum#_CPPv4I0EN5enoki4hsumE7value_tI5ArrayE5Array) writes:
```cpp
template<typename Array>
value_t<Array> hsum(Array value)
```
However, `hsum(DiffArray<CUDAArray<float>> value)` returns still `DiffArray<CUDAArray<float>>`, not `value_t<DiffArray<CUDAArray<float>>>`, which is `float`.
Example code:
```cpp
DiffArray<CUDAArray<float>> dc = 1.f;
value_t<DiffArray<CUDAArray<float>>> vdc = hsum(dc);
```
compiler complains:
```
error: no viable conversion from 'enoki::DiffArray<CUDAArray<float>>' to 'value_t<DiffArray<CUDAArray<float>>>' (aka 'float')
        value_t<DiffArray<CUDAArray<float>>> vdc = hsum(dc);
                                             ^     ~~~~~~~~
```
Possible relevant function: in `include/enoki/autodiff.h, line 1052`:
```cpp
DiffArray hsum_() const {
        if constexpr (is_mask_v<Type> || std::is_pointer_v<Scalar>) {
            fail_unsupported("hsum_");
        } else {
            Index index_new = 0;
            if constexpr (Enabled)
                index_new = tape()->append("hsum", 1, m_index, 1.f);

	    std::cout << "here" << std::endl;

            return DiffArray::create(index_new, hsum(m_value));
        }
    }
```
which returns a `DiffArray`.
`detach(DiffArray<CUDAArray<float>> value)` returns `CUDAArray<float>`, but `hsum(CUDAArray<float> value)` returns still `CUDAArray<float>`, not `value_t<CUDAArray<float>>`, which is `float`:
```
error: no viable conversion from 'enoki::CUDAArray<float>' to 'value_t<CUDAArray<float>>' (aka 'float')
        value_t<CUDAArray<float>> vc = hsum(detach(dc));
                                  ^    ~~~~~~~~~~~~~~~~
```
Possible relevant function: in `include/enoki/cuda.h, line 639`:
```cpp
CUDAArray hsum_() const {
        size_t n = size();
        if (n == 1) {
            return *this;
        } else {
            eval();
            Value *result = cuda_hsum(n, (const Value *) cuda_var_ptr(m_index));
            return CUDAArray::from_index_(cuda_var_register(Type, 1, result, true));
        }
    }
```
which returns a `CUDAArray`.

This problem should also be present for other relevant functions such as `hmax()` and `hprod()`.

**Comment by Speierers** [comment]
Hi @RiverIntheSky ,

Could you try to call `hsum(detach(dc))`?  It makes sense for the returned value of `hsum` to be a differentiable type if it's input is differentiable.

**Comment by RiverIntheSky** [comment]
> Hi @RiverIntheSky ,
> 
> Could you try to call `hsum(detach(dc))`? It makes sense for the returned value of `hsum` to be a differentiable type if it's input is differentiable.

`hsum(detach(DiffArray<CUDAArray<float>> value))` returns `CUDAArray<float>`, as is stated in the second part:
```
error: no viable conversion from 'enoki::CUDAArray<float>' to 'value_t<CUDAArray<float>>' (aka 'float')
        value_t<CUDAArray<float>> vc = hsum(detach(dc));
                                  ^    ~~~~~~~~~~~~~~~~
```

**Comment by Speierers** [comment]
This is to keep the `hsum` operator asynchronous. You should be able to then access the value you are looking for like this: `vdc[0]`. Does that work for you?

**Comment by RiverIntheSky** [comment]
> This is to keep the `hsum` operator asynchronous. You should be able to then access the value you are looking for like this: `vdc[0]`. Does that work for you?

Yes, in the end I used vdc[0] and it works. But I think the main problem is that the documentation is misleading, I had difficulties understanding the return type of `hsum`

**Comment by Speierers** [comment]
The documentation will be updated in the next release, thanks for pointing this out.
