### ISSUE TITLE
Runtime dynamic dispatch of functions using Enoki?

### ISSUE THREAD

**Issue by amyspark** [mitsuba-renderer/enoki#124]
:wave:

We at Krita are looking for a replacement to Vc that will enable us to support the Arm architecture; mainly for Android, but Apple silicon comes for free as well.

A key requirement is the need for supporting a broad range of instruction sets in the same binary, from SSE2 to AVX2+FMA, and dispatch the call to the correct function. However, I do not see any way to perform this with Enoki. Does it allow such an use case?

**Comment by wjakob** [comment]
It's likely tricky to do such things portably. It's not a feature on the Enoki roadmap.
