### ISSUE TITLE
using enoki with custom matrix class

### ISSUE THREAD

**Issue by samuelpmish** [mitsuba-renderer/enoki#128]
Hi, I'm looking to improve vectorization of some of my material models using enoki. It's been going great so far-- with minimal modification, most of the `enoki`-updated models are fully vectorizing, generating assembly of almost exclusively AVX512 instructions-- wow!

My issue is that my code is implemented on top of a basic matrix class kind of like GLM

```cpp
template <typename T, int m, int n>
struct matrix {
    constexpr T& operator()(int i, int j) { return values[i][j]; }
    constexpr const T& operator()(int i, int j) const { return values[i][j]; }
    T values[m][n];
};

// arithmetic operator overloads, inv(), det(), dot(), etc
```

For most of the models, simply replacing `T = double` by `T = enoki::Array<double, 8>` is sufficient to achieve perfect vectorization, but one of the matrix operator overloads (division of a matrix by a scalar) seems to be conflicting with some of the operator overloads in `enoki`, as shown in this compiler explorer example:

https://godbolt.org/z/o7ze4vGYc

Is there a way to either:
- modify my implementation to resolve this conflict and select my operator/ definitions
- change the type deduction rules in enoki to improve compatibility with user-defined containers

Interestingly, the operator* definitions work out-of-the-box, but the operator/ ones don't.

I also saw that `enoki` also defines its own matrix type, and maybe the solution is to adopt that container instead of the one I have, but that is a much bigger endeavor to replace the entire matrix class (since there are subtle differences in their interfaces).

**Comment by Speierers** [comment]
Hi @samuelpmish ,

I would recommend you switch to the `enoki` Matrix type, or at least take a look at how `operator/` is implemented there.

We are now focussed on the [Dr.Jit library](https://github.com/mitsuba-renderer/drjit)  and won't have time you help you modify the type deduction rules in `enoki` unfortunately.
