### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by MertEnesYurtseven** [mitsuba-renderer/enoki#131]
I am sorry for this silly issue, I found out enoki is what I am looking for weeks, however I could not figure out how to install.

**Comment by njroussel** [comment]
There are no installable CMake targets I believe. You would have change this yourself.

(This project isn't being actively worked on anymore, you might want to check out https://github.com/mitsuba-renderer/drjit if that still fits the bill for whatever you're doing.)
