### ISSUE TITLE
Recommended pattern for memory mapped arrays

### ISSUE THREAD

**Issue by bear24rw** [mitsuba-renderer/enoki#27]
Hi,

I have a 100GB file of floats that I have memory mapped, what would be the recommended pattern for doing things like finding the min and max value or computing a histogram? It seems like DynamicArray is the thing to use but it assumes ownership of the array. I could loop over fixed size chunks and load<>() them into an Array but then I need to deal with the boundary condition at the end if the dataset isn't a multiple of the Array size. What would be your suggestions for this scenario?

**Comment by bbbooo313** [comment]
[oubomenhu.com](oubomenhu.com)  老哥换个友链吗？
联系QQ：1297532431

**Comment by merlinND** [comment]
Hi @bear24rw,

Dynamic arrays offer the `map(ptr, size)` constructor, which does not take ownership of the memory region. Does this work for you? 

https://github.com/mitsuba-renderer/enoki/blob/48dd4c3b2a2c426a9e4f74a764f14b2491e41625/include/enoki/dynamic.h#L773

**Comment by bear24rw** [comment]
I think that's exactly what I need, I didn't see that mentioned anywhere in the docs, thanks!
