### ISSUE TITLE
Question: Thread safety

### ISSUE THREAD

**Issue by UNDEFINED-BEHAVIOR** [mitsuba-renderer/enoki#31]
It is possible to seamlessly use normal cpu threading library together with this library?
Or should the array object basically be treated as sequential only, thread-private object?

**Comment by wjakob** [comment]
The SIMD arrays can be used in a multi-threaded context. The JIT compiler that is used to work with CUDA arrays doesn't support multithreading at the moment (though this limitation is likely to be lifted in the future.)
