### ISSUE TITLE
Consider making enoki (cmake) installable

### ISSUE THREAD

**Issue by skgbanga** [mitsuba-renderer/enoki#36]
Hello,

I have started using enoki in my project. Right now, I have basically cloned the entire repo into a subfolder and included enoki in my include paths. (using old cmake way). 

It would be really nice to make it cmake installable. (Internally we use conan as package manager, and making a conan recipe of a project which is cmake installable is straightforward). 

Essentially it would be nice if we can do this:

```
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/my/path/ -G ninja ..
ninja
ninja install
```

I don't know enough cmake to do this myself though :/
PS: Some info: http://mariobadr.com/creating-a-header-only-library-with-cmake.html

**Comment by wjakob** [comment]
Hi @skgbanga,
I would be happy to incorporate such a change, but you'll have to do the CMake changes I fear. I don't need this for any or my projects and am generally pretty busy :-). I'll close this ticket for now since it isn't really an issue of the library itself.
Wenzel

**Comment by skgbanga** [comment]
Fair enough. I will give it a shot.
