### ISSUE TITLE
Prefix sum example?

### ISSUE THREAD

**Issue by AnimatedRNG** [mitsuba-renderer/enoki#40]
After reading through Enoki's documentation, I am still somewhat confused how one would implement a prefix sum or create a summed area table. What is the most idiomatic way to perform a prefix sum?

**Comment by wjakob** [comment]
Only basic reductions (addition, multiplication, max/min, all, none, any) are supported at the moment. AFAIK there isn't an efficient way of doing prefix sum via AVX/SSE, in which case the utility of such a primitive would be in any case dubious.
