### ISSUE TITLE
neigbours on a grid

### ISSUE THREAD

**Issue by nestordemeure** [mitsuba-renderer/enoki#41]
Could Enoki be used to to apply a function to a grid when the function requires access to data points and their neighbors (typically when computing a numerical scheme) ? And what would be the preferred method ?

Should I extract the neighbors manually with a loop (in order to build one array by neighbor position) followed with the function application ?

Or is there a better way ? Maybe using a precomputed array of neighbours index ?

An example would be great as, if it is efficiently doable, that would be a great use case for Enoki.

**Comment by wjakob** [comment]
You can certainly gather() and scatter() from neighboring locations of an array. But what you describe sounds suspiciously like some kind of image processing pipeline, for which a tool like Halide may be preferable.
