### ISSUE TITLE
How to reshape/cut CUDAarray or add two array with different size?

### ISSUE THREAD

**Issue by andyyankai** [mitsuba-renderer/enoki#56]
In c++
FloatC data= (enoki::arange<FloatC>(8)) * 0.f;
FloatC data2 = (enoki::arange<FloatC>(8 * 2)) * 1.f;

How can I do something like:
data = data + data2;
or
data = data + data2[0:8] + data2[8:16];
Thanks!!

**Comment by wjakob** [comment]
Hi @andyyankai  -- you may be able to do something using scatters/gathers but it won't be very efficient.  There is no "native" primitive for this operation because does not follow the spirit of Enoki operations: massive parallelization over vectors without cross-talk between SIMD lanes.
