### ISSUE TITLE
[Enhancement]: Conventions

### ISSUE THREAD

**Issue by matt77hias** [mitsuba-renderer/enoki#58]
This library seems to use the following conventions:
* column-vectors (*);
* row-major storage order for matrices (*);
* right-handed coordinate system.

(*) Ensures fast matrix-column-vector multiplications.

Any possibility of providing support for the exact opposites of these as well:
* row-vectors (**);
* column-major storage order for matrices (**);
* left-handed coordinate system.

(**) Ensures fast row-vector-matrix multiplications.

**Comment by wjakob** [comment]
Hi Matthias,

I don't think this would be difficult to do -- basically just a thorough pass over `matrix.h`. I don't plan on shipping such a feature in the library, though you're welcome to fork Enoki to include something like that.

Best,
Wenzel
