### ISSUE TITLE
Define an emply mask or array with a size?

### ISSUE THREAD

**Issue by andyyankai** [mitsuba-renderer/enoki#59]
Hi,
May I ask how to define an emply mask or array?
for example:
MaskC c{true, true, true, true, true};
can I write it into something like:
MaskC c = MaskC(value = true, size = 5);

**Comment by andyyankai** [comment]
I see there is a zero<FloatD>(int size), not sure if this is work

**Comment by wjakob** [comment]
There is also `full<>`, which should work. Let me know if it doesn't.

**Comment by andyyankai** [comment]
Thanks both method is work,
`FloatD buf = full<FloatD>(10, 4);`
buf is [10, 10, 10, 10]
`MaskC c = zero<MaskC>(10);`
c is [0,0,0,0,0,0,0,0,0,0]
