### ISSUE TITLE
How to merge a large cuda array?

### ISSUE THREAD

**Issue by andyyankai** [mitsuba-renderer/enoki#60]
The question might be a little confusing but it is something related to rendering an image on GPU. Is there any suggestion on how to do that?
for example, if a want to render an image 600\*800 with 32spp, is it a wise idea to create a CUDA array with size 600\*800\*32?(just assume the GPU can handle that) and use some method to take the average of that into a 600\*800 size array? Is there any function to do that?
Also, the Cuda array has a gradient.
Thanks

**Comment by merlinND** [comment]
Depending on how you structure your computation, you may have to do both. For example,

1. First do all per-sample computation in parallel, storing the per sample computation in a 600x800x32 array
2. Then accumulate and average the result to the image, e.g. using `enoki::scatter_add`

You could also decide to split your computation differently and repeat step (1) for each spp, then you would never have to create the larger array. In general, more parallelism is better, except when you run out of memory.

**Comment by andyyankai** [comment]
My code
`
FloatD Render::run() {
	Sampler s = Sampler(8);
    int spp = 1024;
	MaskC c = !zero<MaskC>(m_height * m_weight);
    FloatD rs = full<FloatD>(0.0f, m_height * m_weight);
    Int32D index = arange<Int32D>(m_height * m_weight);  

    for(int i=0; i<spp; ++i) {
        FloatD rnd = s.next_float(c)/spp;
        scatter_add(rs,rnd,index);
    }
    return rs;
};
`
python:
`
img = r.run()
print("done")
img = img.numpy() # this step can take a long long time if spp is high
`

However, this seems not a very efficient way to return the result. Is there any suggestion on how to fix this problem and optimize the code?
