### ISSUE TITLE
Dynamic Complex Arrays

### ISSUE THREAD

**Issue by gergol** [mitsuba-renderer/enoki#61]
What's the correct way to work with dynamic arrays of complex numbers? 

AFAICS there are two possible ways: `Complex<DynamicArray<FloatP>>` and`DynamicArray<Complex<FloatP>>`. The first seems to work somehow, but unfortunately it is not possible to use the `map` function with it. The second version, on the other hand, allows me to map existing memory but fails with most other functions. 

Thanks in advance!

**Comment by wjakob** [comment]
Complex<DynamicArray<FloatP>> is the way to go. Dynamic arrays always come at the deepest level of the hierarchy. What is the problem with the `map` function? (I assume you mean `vectorize`?)

**Comment by gergol** [comment]
Thanks for the quick reply! Sorry for being unclear. I mean the the `DynamicArray::map` function. My goal is to be able to use the output of an FFT with enoki.

**Comment by wjakob** [comment]
Enoki assumes that the data is arranged in SoA format. In that case, you should be able to map the two components of your complex vector without problems (with two `map` calls). If the data is interleaved, you will need to `gather` each component.

**Comment by gergol** [comment]
So here is how I try to do it:
```
using namespace enoki;
{
  using FloatP   = Packet<float, 8>;
  using FloatX  = DynamicArray<FloatP>;
  using ComplexX = Complex<FloatX>;

  std::vector<float> interleaved;

  auto cplx = ComplexX::map(interleaved.data(), 10);

}
```

However, the last line fails to compile with `error: no member named 'map' in `enoki::Complex<enoki::DynamicArray<enoki::Packet<float, 8, true, enoki::RoundingMode::Default> >, true>'; did you mean 'max'`.

**Comment by wjakob** [comment]
As I said -- you need a map *per* component (`FloatX::map`) or two `FloatX` gathers in the interleaved case.

**Comment by gergol** [comment]
OK, I see. I was thinking there was a way to do something similar to a `reinterpret_cast<complex<float>>`. Thanks for your help!
