### ISSUE TITLE
How to cast a int* to FloatC?

### ISSUE THREAD

**Issue by andyyankai** [mitsuba-renderer/enoki#64]
For example, if I have an int* like an int array
How can I cast that int array into a FloatC/FloatD, which is a cuda_array in enoki efficiently? I don't think it is a good idea to scatter_add each element in that int array to enoki cuda_array.
Thanks

**Comment by Speierers** [comment]
I believe you can do something like this:

```c++
using IntC = enoki::CUDAArray<int>;
using FloatC = enoki::CUDAArray<float>;

size_t size = ...; // Size of my array
int* data = ...; // Points to an array of len == size
IntC data_gpu = IntC::copy(data, size);

// Then cast it to Float values
FloatC data_gpu_float = FloatC(data_gpu);
```

Is this what you are looking for?

**Comment by andyyankai** [comment]
Yes, the copy() is really helpful. Thanks!
