### ISSUE TITLE
Enoki can'nt be used on MSVC2019

### ISSUE THREAD

**Issue by qatnonoil** [mitsuba-renderer/enoki#65]
I can'nt use Enoki(release 0.1) on VC2019.
Here is the smallest reproduction code
```
enoki::Packet<float, 8> x(1.0f);
enoki::pow(x, x);
```
Thanks.

**Comment by merlinND** [comment]
Hello @qatnonoil,

Could you please copy the full compilation error / runtime error that you are encountering?
As well as the full version number os MSVC that you are using.

**Comment by qatnonoil** [comment]
Hi, @merlinND
Visual Studio 2019 version 16.4.6( _MSC_VER == 1924)
[enoki.log](https://github.com/mitsuba-renderer/enoki/files/4355354/enoki.log) (Sorrry for Japanese)

**Comment by merlinND** [comment]
From the log, I'm afraid can't really understand the error. Would it be possible to produce this log with English error messages ?

The two lines of code that you sent compile on Linux, and I don't have access to a Windows machine at the moment.

A couple more things:

1. Could you please send the full minimum reproducing example (with main & includes)?
2. What are the SIMD features supported by your CPU: AVX2, AVX512, other? I'm surprised to see `enoki::StaticArrayBase<float,1,true,enoki::RoundingMode::Default,false,Derived_>` in the error messages. 
3. Are you trying to compile inside of a VM?
4. Does it work when compiling with `-DENOKI_DISABLE_VECTORIZATION=1`?

**Comment by wjakob** [comment]
@qatnonoil? Also, are you sure that this is really the latest master version? There were some issues with the functions you mentioned in a previous commit on MSVC, but `master` should work.

**Comment by qatnonoil** [comment]
@wjakob @merlinND 
I used the latest commit (02b224da) and it worked without any problem! 
I'm waiting for it to be released. 
Thanks.
