### ISSUE TITLE
Is there any suggestion on how to auto diff a Vector3fC?

### ISSUE THREAD

**Issue by andyyankai** [mitsuba-renderer/enoki#67]
![image](https://user-images.githubusercontent.com/28462736/77785705-cb911e00-7019-11ea-81bf-b93de6a64f2b.png)

It seems I cannot backward the Vector3fC, only FloatC. I tried to autodiff each index for the Vector3fC but hoping there is a better way.

**Comment by andyyankai** [comment]
I believe b should always be a FloatD..

**Comment by arpit15** [comment]
@andyyankai I believe that this problem is due to difference b/w `Float32` and `Vector3f` types. You can perform your computation using code 
```
Float32 a(1,2,3);
set_requires_gradient(a);
auto b = 2*a*a + 3;
backward(b);
cout << gradient(a) << endl;
```
