### ISSUE TITLE
Is enoki support array index?

### ISSUE THREAD

**Issue by andyyankai** [mitsuba-renderer/enoki#68]
for example
A = [1, 2, 3, 4, 5]
I = [0, 1, 1, 2]
then A[I] = [A[0], A[1], A[1], A[2]] = [1, 2, 2, 3]

or

	    FloatD some = {2.3f, 3.4f, 4.5f, 5.6f, 6.7f, 7.8f};
	    IntC index = {1,1,3,3,5};

	    FloatD check = some[index];

	    value of check should be: [3.4f, 3.4f, 5.6f, 5.6f, 7.8f]

**Comment by mp3guy** [comment]
This is the gather operation. But, it probably isn't as fast as you might want it to be.

**Comment by Speierers** [comment]
Indeed, you will need a `gather` operator to do this (see [this](https://enoki.readthedocs.io/en/master/reference.html?highlight=gather#_CPPv4I0_6size_t0EN5enoki6gatherE5ArrayPKv5Index6mask_tI5ArrayE))

In your code this should translate to:
```
FloatD some = {2.3f, 3.4f, 4.5f, 5.6f, 6.7f, 7.8f};
IntC index = {1,1,3,3,5};
FloatD check = gather<FloatD>(some, index); // or something very similar to this
```

**Comment by andyyankai** [comment]
When I tried:
'FloatC some = {2.3f, 3.4f, 4.5f, 5.6f, 6.7f, 7.8f};
IntC index = {1,1,3,3,5};
FloatC check = gather<FloatC>(some, index);'
its working, but when I change FloatC into FloatD I have an error:
![image](https://user-images.githubusercontent.com/28462736/77890230-02d31b00-7224-11ea-9ef3-4d1ed188fc89.png)

**Comment by Speierers** [comment]
Could you try with `IntD` instead of `IntC` when working with `FloatD`?

**Comment by andyyankai** [comment]
Yes, seems working now.
