### ISSUE TITLE
<from enoki import *> imports only few names

### ISSUE THREAD

**Issue by lvjiahui** [mitsuba-renderer/enoki#69]
After I following the enoki document `GPU Arrays`([https://enoki.readthedocs.io/en/master/gpu.html#](url))

```
cd <path-to-enoki>
mkdir build
cmake -DENOKI_CUDA=ON -DENOKI_AUTODIFF=ON -DENOKI_PYTHON=ON ..
make
```

In python:
```
>>> from enoki import *
```

I find only few names imported, without `FloatC`, `cuda_set_log_level`.
```
['CPUBuffer',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'allclose',
 'arange',
 'core',
 'e',
 'empty',
 'full',
 'inf',
 'linspace',
 'nan',
 'pi',
 'zero']
```
Did i miss something? Or the code only for demonstration? 
Thanks!

**Comment by lvjiahui** [comment]
By the way, I can find
`libenoki-cuda.so`
`libenoki-cuda.so`
but no
`enoki.cpyhon-37m-x86_64-linux-gnu.so (platform-dependent filename)`

**Comment by lvjiahui** [comment]
After some experiment, I change the __init__.py to
```
@@ -1 +1,6 @@
-__import__("enoki.core")
+from . import core
+from . import cuda
+from . import cuda_autodiff
+from . import dynamic
+from . import scalar
+__import__("enoki.core")
```

It seems to do the job, although I am not sure it is the best way

**Comment by Speierers** [comment]
Hi @lvjiahui,
Thanks for pointing this out. Indeed the documentation isn't up-to-date.

The Enoki's Python library is now divided into different submodules: 
```
enoki.scalar
enoki.dynamic
enoki.cuda
enoki.cuda_autodiff
```

Each one of those have their version of `Float32`, `Vector3f`, ...
Therefore, to get a `CUDAArray` in Python you could do the following:
```
from enoki.cuda import Float32 as FloatC
```

I will update the documentation.

**Comment by lvjiahui** [comment]
The document is of high quality and instructive，Thanks again!
