### ISSUE TITLE
How about the efficiency?

### ISSUE THREAD

**Issue by yangfengzzz** [mitsuba-renderer/enoki#72]
I really like the enoki with the template design which can be used on multiple platform and autodiff. I want to use this as the base of my fluid simulation code. so I just make a little tests about the efficiency:
```c++
std::array<float, 3> srgb_gamma(std::array<float, 3> x) {
    std::array<float, 3> result;
    for (int i = 0; i < 3; i++) {
        if (x[i] <= 0.0031308f)
           result[i] = x[i] * 12.92f;
        else
           result[i] = std::pow(x[i] * 1.055f, 1.f / 2.4f) - 0.055f;
    }
    return result;
}
```

I handwrite a function and compare the code given in the tutorial, I loop for 10000times and find my test is 100x faster than enoki(without -msse4), 20xfaster(with -msse4), I can't figure out why? Does I miss something in compile flag?

**Comment by wjakob** [comment]
Hi @yangfengzzz,

it sounds highly unlikely. Can you post the full compilation options including a full example that computes the timings? Note that measuring the time of simple functions can be challenging to do unless you set things up very carefully because the compiler notices irrelevant computation that is subsequently optimized away.

Wenzel

**Comment by yangfengzzz** [comment]
@wjakob 

<img width="715" alt="截屏2020-03-31 下午5 01 41" src="https://user-images.githubusercontent.com/5378042/78008127-dcbb9100-7371-11ea-81b1-c082d07e076b.png">

`   double durationInSeconds() const {
      auto end = std::chrono::steady_clock::now();
      long long count = std::chrono::duration_cast<std::chrono::microseconds>(
         end - _startingPoint).count();
      return count / 1000000.0;
   }
    //! Resets the timer.
   void reset() {
      _startingPoint = _clock.now();
   }`

This is my simple code, I think there must be wrong somewhere, but the time is 0.903766 vs 0.008044 in debug mode(without any compile flag) 

I use Xcode as IDE and new MacOS System so I think the compiler is not old version. Thank you very much!

**Comment by wjakob** [comment]
There are elementary mistakes here, I suggest that you read up on microbenchmarks in C/C++. For example, you are not using the result of the computation, so parts of it are likely optimized away by the compiler. Another issue is that Enoki mainly pays off when you are working with packets, so `Array<Array<float>, 3>` and not `Array<float, 3>`.
