### ISSUE TITLE
question about multi-core and multi GPU

### ISSUE THREAD

**Issue by lvjiahui** [mitsuba-renderer/enoki#74]
- I am importing the Enoki in python and using dynamic array. I find it only uses one core of cpu.
Should I use multithread myself or Enoki surpport multi-core parallal?

- I have multi GPU,  can I specify which GPU Enoki uses?

Thanks for your help!

**Comment by Speierers** [comment]
Dynamic arrays in Enoki do not take advantage of multiple cores on the CPU. For this you will have to parallelize your code manually.

I believe you should be able to select a GPU with the environement variable `CUDA_VISIBLE_DEVICES=GPU_ID`. Let me know if this works for you.

**Comment by lvjiahui** [comment]
```
CUDA_VISIBLE_DEVICES=GPU_ID python
```
It works.
thanks!
