### ISSUE TITLE
conversion from FloatD to FloatC?

### ISSUE THREAD

**Issue by andyyankai** [mitsuba-renderer/enoki#76]
e.g.
FloatD cuda_diff = ...;
FloatC cuda = cuda_diff.val();
or
Vector3fD 3d_diff = ...;
Vector3fC 3d = 3d_diff.val();

**Comment by merlinND** [comment]
The following will return a (non-differentiable) `FloatC` from a `FloatD`:

```cpp
FloatC x = detach(y);
```
