### ISSUE TITLE
Using Mask to fliter an array

### ISSUE THREAD

**Issue by andyyankai** [mitsuba-renderer/enoki#78]
For example:
FloatC arr = {0.0f, 1.0f, 2.0f, 3.0f, 4.0f};
MaskC msk = {0, 0, 1, 1, 0};
FloatC flitered_arr = do_something(arr, msk);
flitered_arr is {0.0f, 0.0f, 2.0f, 3.0f, 0.0f};
or
FloatC flitered_arr = do_something2(5.0f, arr, msk);
flitered_arr is {5.0f, 5.0f, 2.0f, 3.0f, 5.0f};

**Comment by andyyankai** [comment]
nvm, all of these are on https://enoki.readthedocs.io/en/master/basics.html

**Comment by andyyankai** [comment]
I am currently using f1[f1 > 0.f] = f2; as written on page https://enoki.readthedocs.io/en/master/basics.html
let me know if there is a better solution especially using gpu

**Comment by Speierers** [comment]
There is no better way on GPU.
