### ISSUE TITLE
Incorrect behaviour for select with scalar inputs

### ISSUE THREAD

**Issue by arpit15** [mitsuba-renderer/enoki#79]
In python, `ek.select(True, 0.1, 0.2)` outputs [1] of type `scalar.Vector1m` 

Adding the following binding code in `src/python/scalar.cpp` solves the bug.
```
m.def("select", [](bool a, Float b, Float c) {
        return enoki::select(a, b, c);
});
```
Please verify if this is the correct way to add binding to scalar for `select` function.

**Comment by Speierers** [comment]
This is now fixed, thanks!
