### ISSUE TITLE
Question: Other Backend (OpenCL, DirectCompute, ...) [Nice to have]

### ISSUE THREAD

**Issue by soufianekhiat** [mitsuba-renderer/enoki#80]
Having other backend: DirectX HLSL Direct Compute, OpenCL, Compute OpenGL, ...
Could you explain what is needed to implement another GPUArray (CLArray, DxArray, ...). Or GPUArray which can target CUDA, OpenCL, ... At compile time.

**Comment by wjakob** [comment]
An upcoming version of Enoki is in the works, which will have a LLVM-based backend that compiles to vectorized CPU code (AVX, AVX512, etc.) analogous to the current CUDA array. That's it for now -- my time to work on Enoki is limited, and I don't plan on pursuing DirectX/Metal. Outside contributions are welcomed though!
